name: AMP Console Package

on:
  pull_request:
    branches: ["main"]
    paths:
      - "console/**"
      - ".github/workflows/amp-console-package-pr-checks.yaml"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: console
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.14.0"

      - name: Install Rush dependencies
        run: node common/scripts/install-run-rush.js install

      - name: Run Rush lint
        run: node common/scripts/install-run-rush.js lint

  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: console
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.14.0"

      - name: Install Rush dependencies
        run: node common/scripts/install-run-rush.js install

      - name: Run Rush build
        run: node common/scripts/install-run-rush.js build
